### ISSUE TITLE
Skill Labels proper handling

### ISSUE THREAD

**Issue by StefanoSoffiaUTRC** [CARVE-ROBMOSYS/BTCompiler#3]
As a reminder from previous phone conversation.

The BT interpreter shall be parametric (no re-extraction required) w.r.t. the set of skills. Each skill shall be uniquely identified by a name, or mnemonic identifier, i.e. a string. It can be assumed that the BT description, i.e. the XML, includes the names of the referenced skills.

**Comment by altacch** [comment]
@CARVE-ROBMOSYS/all 
I would like to propose the following workflow for the generation of the BT interpreter.

* The user writes down an XML file with a list of all the basic skills that will be used in his BTs (as I did in [this file](https://github.com/CARVE-ROBMOSYS/BTCompiler/blob/master/infra/sklist.xml) for our use cases)
* The user executes (on a system where the OCaml compiler is available) a program which produces a shared library object (say "btinterp.so")
* The user uploads the library file on the hardware where Smartsoft runs
* From that point on, the user can call the BT interpreter from C code in Smartsoft; the interpreter can read and execute any BT whose skills are a subset of the ones previously specified.

Is such a workflow acceptable? If the answer is yes, we do not actually need any refactoring of our current Coq codebase.

**Comment by altacch** [comment]
I can confirm that the workflow delineated above seems feasible. In the repo you can find [a first version](https://github.com/CARVE-ROBMOSYS/BTCompiler/blob/master/infra/interpreter.ml) of a program to load a BT from an XML file (this will be needed for both the interpreter and the spec extractor). In order to compile it, follow these steps:

1. in the main directory, type `coqc bt.v shallow.v` (this generates the OCaml module `btsem`)
2. in the `infra` directory, build the skill reader program with `ocamlfind ocamlopt -package xmlm -linkpkg readskill.ml -o rs`
3. execute the skill reader program with `rs sklist.xml` (this will generate the OCaml module `skills`)
4. build the loader with:
    ```
    ocamlopt -c btsem.mli btsem.ml skills.ml
    ocamlfind ocamlopt -package xmlm -linkpkg btsem.cmx skills.cmx interpreter.ml -o int
    ```
Then you can execute the resulting program on the example trees contained in the files `uc?.xml` (but don't expect much from the output...)

Next steps are:
1. set up an automated build system (as it is obvious from the above instructions, this is badly needed!)
2. understand OCaml's foreign function interface in order to make the resulting program/library interoperate with C code

**Comment by altacch** [comment]
Quick update: the build system is there, just run `make` in the top directory to build the Coq sources, then
```
cd infra
make readskill
./readskill.native sklist.xml
make interp
```
to build the (mock) interpreter.

Making progress also on point 2, but this needs a little more time...

**Comment by altacch** [comment]
It seems that the above workflow will be the final one, so I'm closing this issue.
